### PR TITLE
PRODTASKS-328

### PR DESCRIPTION
**Pull request by jcoleman0redhat0com**
Don't show imported artifacts that were also built in an earlier build.

### CODE REVIEW

**Comment by rnc** [comment]
add to whitelist

**Comment by rnc** [comment]
ok to test

**Comment by dwalluck** [comment]
retest this please

**Comment by dwalluck** [comment]
retest this please

**Comment by dwalluck** [comment]
retest this please

**Comment by dwalluck** [comment]
When merging, I would squash the commit and remove the last two commit messages.

**Comment by dwalluck** [comment]
retest this please

**Comment by bxf12315** [comment]
retest this please

**Comment by bxf12315** [comment]
retest this please

**Comment by bxf12315** [comment]
retest this please

**Comment by rnc** [comment]
+1

**Comment by rnc** [comment]
Can we merge this now or are more changes needed?

**Comment by dwalluck** [comment]
I've merged it and it passes the test which uses two commons-lang builds, one imported, and one not and you gave it +1 but @jcoleman0redhat0com has not commented.

**Pull request merged**
