### PR TITLE
PRODTASKS-297: Default to all Koji archive types if provided list is empty

### PR DESCRIPTION
**Pull request by dwalluck**
…empty

### CODE REVIEW

**Comment by ausil** [comment]
what is PRODTASKS-297?

**Comment by rnc** [comment]
@ausil Internal JIRA reference. Please contact myself or @dwalluck on internal IRC for further details.

**Comment by ausil** [comment]
@rnc lets keep those internal and reference something public and accessible please

**Comment by dwalluck** [comment]
retest this please

**Comment by rnc** [comment]
retest this please

**Pull request merged**
