### PR TITLE
Remove reliance on commons-lang3. Rely on releng parent for plugin ve…

### PR DESCRIPTION
**Pull request by rnc**
…rsioning. 

Also src/bin descriptors.

### CODE REVIEW

**Comment by rnc** [comment]
@dwalluck We could consider upgrading the releng parent versions perhaps. It appears the version of the assembly plugin caused the slowdown.

**Comment by dwalluck** [comment]
I started off not using any parent, so I wanted to manage all versions. Also, everything was at the latest versions. Are you saying it now uses an older version of the assembly plugin?

**Comment by dwalluck** [comment]
This change doesn't seem to change the build time for me at all.

**Comment by rnc** [comment]
time mvn clean install (no changes):
[INFO] Total time: 02:00 min
[INFO] Finished at: 2017-11-20T07:50:10Z
[INFO] Final Memory: 215M/1473M
166.10s user 1.92s system 137% cpu 2:01.97 total

time mvn clean install (with just the assembly plugin and descriptor changes):
[INFO] Total time: 16.627 s
[INFO] Finished at: 2017-11-20T07:51:02Z
[INFO] Final Memory: 85M/923M
50.02s user 1.21s system 287% cpu 17.832 total

**Pull request merged**
