### PR TITLE
GH-91: Fix java.lang.ArithmeticException in findBuilds

### LINKED ISSUE #91: Exception in thread "main" java.lang.ArithmeticException: Cannot divide by zero
Every time koji-build-finder is called it logs an exception:
```
Exception in thread "main" java.lang.ArithmeticException: Cannot divide by zero
	at java.time.Duration.dividedBy(Duration.java:977)
	at com.redhat.red.build.finder.BuildFinder.findBuilds(BuildFinder.java:390)
	at com.redhat.red.build.finder.Main.main(Main.java:340)
```

### PR DESCRIPTION
**Pull request by dwalluck**
Closes #91.

### CODE REVIEW

**Comment by rnc** [comment]
@dwalluck  Can we add a test case please to verify this doesn't happen again ? Why does Main catch and print the IOException rather than propagating it out ?

**Comment by dwalluck** [comment]
> @dwalluck Can we add a test case please to verify this doesn't happen again ? Why does Main catch and print the IOException rather than propagating it out ?

Unless this particular code occurs offline entirely, it will have to be one of these mocked online tests which takes a lot of code and requires access to the Koji server to create the test I/O.

In `main()`, there is nowhere left to propagate to except the JVM itself. I think at that point is should be logging the exception and exiting the JVM.

Do you want the signature to be

`public static void main(String[] args) throws IOException`

instead of

`public static void main(String[] args)`

and what are the advantages?

**Comment by dwalluck** [comment]
@bxf12315 retest this please

**Comment by rnc** [comment]
@dwalluck If we catch an IOException but don't handle it (i.e. by either propagating it or calling System.exit(1)) then the program has an incorrect return code?

**Comment by rnc** [comment]
@dwalluck Re testing this .... something hacked together like 
```
+
 +    @Test
 +    public void verifyArithmeticException() throws Exception {
 +        final String checksum = "2e7e85f0ee97afde716231a6c792492a";
 +        MockKojiClientSession session = new MockKojiClientSession("skip-import-test");
 +        BuildConfig config = new BuildConfig();
 +        BuildFinder finder = new BuildFinder(session, config);
 +        Map<String, Collection<String>> checksumTable = new HashMap<>();
 +        checksumTable.put(checksum, new HashSet<>());
 +        finder.findBuilds(checksumTable);
 +    }
```
would verify that ArithmeticException is not thrown ?

**Comment by dwalluck** [comment]
> @dwalluck Re testing this .... something hacked together like

This is already added in https://github.com/release-engineering/koji-build-finder/pull/92/commits/ec16448395b02a530539d43b958d8ce177eafd7a. It simulates a call to a non-existing checkum "abc" which returns an "empty" response. This causes the builds to be empty which triggers the exception in the original code.

**Comment by dwalluck** [comment]
> @dwalluck If we catch an IOException but don't handle it (i.e. by either propagating it or calling System.exit(1)) then the program has an incorrect return code?

How about adding `System.exit(1)` after https://github.com/release-engineering/koji-build-finder/blob/ab9034167e3d46447ad276d8d84c5d7978d20988/src/main/java/com/redhat/red/build/finder/Main.java#L364-L365

The `usage()` method https://github.com/release-engineering/koji-build-finder/blob/ab9034167e3d46447ad276d8d84c5d7978d20988/src/main/java/com/redhat/red/build/finder/Main.java#L366-L369

already calls `System.exit(1)` 

https://github.com/release-engineering/koji-build-finder/blob/ab9034167e3d46447ad276d8d84c5d7978d20988/src/main/java/com/redhat/red/build/finder/Main.java#L80-L82

so this change would make it consistent with that.

This should be a separate pull request, I think, though.

In the next micro release, we can improve the handling in `BuildFinder` which is just logging and continuing on Koji client errors right now, but should probably exit on the first error instead.

**Comment by dwalluck** [comment]
@rnc Given the above, is this ready to be merged?

**Comment by dwalluck** [comment]
Issue #98 filed concerning exceptions.

**Comment by rnc** [comment]
@dwalluck  +1 , especially given you have created #98.

**Pull request merged**
