### PR TITLE
Ignore unknown properties when parsing configuration JSON

### PR DESCRIPTION
**Pull request by dwalluck**

### CODE REVIEW

**Comment by dwalluck** [comment]
The reason for this fix is that as we add new configuration, etc., options, it would be good if the new JSON files could still be loaded by an older version of the software.

For version 1.1, we should add method for loading the configuration file that adds this property without having to add it to the test itself. But, I didn't want to change the API for version 1.0.1.

**Comment by dwalluck** [comment]
There is also a "bug" where the tests call `main()` and `main()` will try to load a default configuration file if it exists on the local system. This causes problems when testing locally.

I think that the easiest fix right now is for the tests to use an explicit configuration file from the test resources directory to workaround this issue, but the core issue still remains.

**Comment by dwalluck** [comment]
@rnc Is there any drawback to setting `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` to `false`?

**Comment by rnc** [comment]
I think this makes sense to set that.

**Comment by dwalluck** [comment]
> I think this makes sense to set that.

Currently, the test is only there for config, but I've enabled the option for checksums and builds as well.

**Pull request merged**
