### PR TITLE
PRODTASKS-305: PNC sources not found

### PR DESCRIPTION
**Pull request by dwalluck**

### CODE REVIEW

**Comment by rnc** [comment]
retest this please

**Comment by rnc** [comment]
retest this please

**Comment by rnc** [comment]
@jdcasey Examining the CI output I am seeing 
```
[INFO] Downloading: http://indy:8080/api/group/public/com/redhat/red/build/kojiji/2.0-SNAPSHOT/maven-metadata.xml

[WARNING] Checksum validation failed, expected <?xml but is 11860d522f3dc21252f064c4bf46316950be2549 for http://indy:8080/api/group/public/com/redhat/red/build/kojiji/2.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not validate integrity of download from http://indy:8080/api/group/public/com/redhat/red/build/kojiji/2.0-SNAPSHOT/maven-metadata.xml: Checksum validation failed, expected <?xml but is 11860d522f3dc21252f064c4bf46316950be2549
[WARNING] Checksum validation failed, expected <?xml but is 11860d522f3dc21252f064c4bf46316950be2549 for http://indy:8080/api/group/public/com/redhat/red/build/kojiji/2.0-SNAPSHOT/maven-metadata.xml
```

Unfortunately I am unable to examine the Indy instance - it doesn't appear to be fetching the new SNAPSHOTs from sonatype - a new SNAPSHOT of kojij has been deployed to https://oss.sonatype.org/content/repositories/snapshots/com/redhat/red/build/kojiji/2.0-SNAPSHOT/maven-metadata.xml

**Comment by jdcasey** [comment]
retest this please

**Comment by jdcasey** [comment]
retest this please

**Pull request merged**
